test_zip_codes = ['44618', '44647', '44691', '44646', '44667', '44709', '44718', '44666', '44805', '44677',
                          '44614', '44721',
                          '44652', '44720', '44645', '44848', '44630', '44866', '44287', '44276', '44232', '44216',
                          '44214', '44217',
                          '44685', '44270', '44632', '44230', '44874', '44319', '44640', '44312', '44282', '44250',
                          '44203', '44837',
                          '44859', '44273', '44201', '44251', '44235', '44880', '44260', '44265', '44306', '44322',
                          '44314', '44254',
                          '44301', '44281', '44393', '44399', '44311', '44215', '44307', '44320', '44305', '44309',
                          '44315', '44316',
                          '44317', '44325', '44326', '44328', '44334', '44372', '44396', '44398', '44308', '44304',
                          '44321', '44302',
                          '44272', '44274', '44275', '44303', '44310', '44278', '44855', '44851', '44258', '44313',
                          '44240', '44221',
                          '44262', '44256', '44242', '44243', '44210', '44285', '44222', '44211', '44333', '44266',
                          '44253', '44090',
                          '44223', '44224', '44857', '44264']

test_hospitals = [{'attributes': {'OBJECTID': 3758, 'ID': '0016344646', 'NAME': 'AFFINITY MEDICAL CENTER',
                                     'ADDRESS': '875 EIGHTH STREET NE', 'CITY': 'MASSILLON', 'STATE': 'OH',
                                     'ZIP': '44646', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 837-6863',
                                     'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 156,
                                     'COUNTY': 'STARK', 'COUNTYFIPS': '39151', 'COUNTRY': 'USA',
                                     'LATITUDE': 40.8063802450001, 'LONGITUDE': -81.517451361, 'NAICS_CODE': '622110',
                                     'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                     'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                     'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                     'WEBSITE': 'http://www.affinitymedicalcenter.com', 'STATE_ID': '1272',
                                     'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                     'TTL_STAFF': -999, 'BEDS': 156, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 5844, 'ID': '0000844805',
                                        'NAME': 'UNIVERSITY HOSPITALS SAMARITAN MEDICAL', 'ADDRESS': '1025 CENTER ST',
                                        'CITY': 'ASHLAND', 'STATE': 'OH', 'ZIP': '44805', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(419) 289-0491', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 123, 'COUNTY': 'ASHLAND', 'COUNTYFIPS': '39005', 'COUNTRY': 'USA',
                                        'LATITUDE': 40.859228973, 'LONGITUDE': -82.3095378579999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.samaritanhospital.org', 'STATE_ID': '1104',
                                        'ALT_NAME': 'SAMARITAN HOSPITAL - PEOPLES HOSPITAL', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 123,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6071, 'ID': '0029944646', 'NAME': 'AULTMAN HOSPITAL WEST',
                                        'ADDRESS': '2051 WALES AVENUE NW', 'CITY': 'MASSILLON', 'STATE': 'OH',
                                        'ZIP': '44646', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 497-3966',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 8,
                                        'COUNTY': 'STARK', 'COUNTYFIPS': '39151', 'COUNTRY': 'USA',
                                        'LATITUDE': 40.822193343, 'LONGITUDE': -81.50451061, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1474416000000, 'WEBSITE': 'https://aultman.org', 'STATE_ID': '1443',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 8, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 6790, 'ID': '0015944667', 'NAME': 'AULTMAN ORRVILLE HOSPITAL',
                                        'ADDRESS': '832 SOUTH MAIN STREET', 'CITY': 'ORRVILLE', 'STATE': 'OH',
                                        'ZIP': '44667', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 682-3010',
                                        'TYPE': 'CRITICAL ACCESS', 'STATUS': 'OPEN', 'POPULATION': 34,
                                        'COUNTY': 'WAYNE', 'COUNTYFIPS': '39169', 'COUNTRY': 'USA',
                                        'LATITUDE': 40.8321823480001, 'LONGITUDE': -81.763682683,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.aultmanorrville.org', 'STATE_ID': '1291',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 34, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6791, 'ID': '0004244691', 'NAME': 'WOOSTER COMMUNITY HOSPITAL',
                                        'ADDRESS': '1761 BEALL AVENUE', 'CITY': 'WOOSTER', 'STATE': 'OH',
                                        'ZIP': '44691', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 263-8100',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 150,
                                        'COUNTY': 'WAYNE', 'COUNTYFIPS': '39169', 'COUNTRY': 'USA',
                                        'LATITUDE': 40.820887467, 'LONGITUDE': -81.932161465, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391472000000,
                                        'WEBSITE': 'http://www.woosterhospital.org', 'STATE_ID': '1292',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'GOVERNMENT - LOCAL',
                                        'TTL_STAFF': -999, 'BEDS': 150, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1441, 'ID': '0003744203',
                                        'NAME': 'SUMMA HEALTH SYSTEM BARBERTON HOSPITAL',
                                        'ADDRESS': '155 5TH STREET N E', 'CITY': 'BARBERTON', 'STATE': 'OH',
                                        'ZIP': '44203', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(234) 312-5026',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 271,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.0150713310001, 'LONGITUDE': -81.5889978229999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.summahealth.org/locations/hospitals/barberton',
                                        'STATE_ID': '1279', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 271,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1444, 'ID': '0030044203', 'NAME': 'REGENCY HOSPITAL OF AKRON',
                                        'ADDRESS': '155 FIFTH STREET, NE', 'CITY': 'BARBERTON', 'STATE': 'OH',
                                        'ZIP': '44203', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(717) 975-4503',
                                        'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN', 'POPULATION': 45,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.014583541, 'LONGITUDE': -81.589116796, 'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'EXTENDED CARE HOSPITALS (EXCEPT MENTAL, SUBSTANCE ABUSE)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1474416000000,
                                        'WEBSITE': 'http://barberton.regencyhospital.com/', 'STATE_ID': '1442',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                        'TTL_STAFF': -999, 'BEDS': 45, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6519, 'ID': '0006544254', 'NAME': 'LODI COMMUNITY HOSPITAL',
                                        'ADDRESS': '225 ELYRIA STREET', 'CITY': 'LODI', 'STATE': 'OH', 'ZIP': '44254',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 948-1222',
                                        'TYPE': 'CRITICAL ACCESS', 'STATUS': 'OPEN', 'POPULATION': 20,
                                        'COUNTY': 'MEDINA', 'COUNTYFIPS': '39103', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.0358623180001, 'LONGITUDE': -82.014169286,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.lodihospital.org', 'STATE_ID': '1234',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 20, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6520, 'ID': '0004944281',
                                        'NAME': 'SUMMA WADSWORTH-RITTMAN HOSPITAL', 'ADDRESS': '195 WADSWORTH ROAD',
                                        'CITY': 'WADSWORTH', 'STATE': 'OH', 'ZIP': '44281', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(330) 334-1504', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'CLOSED',
                                        'POPULATION': 50, 'COUNTY': 'MEDINA', 'COUNTYFIPS': '39103', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.028286812, 'LONGITUDE': -81.75161518, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1343001600000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.wrhhs.org', 'STATE_ID': '1235',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 50, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 2490, 'ID': '0010244307', 'NAME': 'AKRON GENERAL MEDICAL CENTER',
                                        'ADDRESS': '1 AKRON GENERAL AVENUE', 'CITY': 'AKRON', 'STATE': 'OH',
                                        'ZIP': '44307', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 344-6000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 532,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.0781231720001, 'LONGITUDE': -81.5313967719999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.akrongeneral.org', 'STATE_ID': '1276',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 532, 'TRAUMA': 'LEVEL I', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3765, 'ID': '0012444309',
                                        'NAME': 'SUMMA HEALTH SYSTEMS AKRON HOSPITAL',
                                        'ADDRESS': '525 EAST MARKET STREET', 'CITY': 'AKRON', 'STATE': 'OH',
                                        'ZIP': '44309', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(234) 312-5026',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 657,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.0811261860001, 'LONGITUDE': -81.499818706,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.summahealth.org', 'STATE_ID': '1275',
                                        'ALT_NAME': 'AKRON CITY HOSPITAL', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 657, 'TRAUMA': 'LEVEL I', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3997, 'ID': '0126144308', 'NAME': "AKRON CHILDREN'S HOSPITAL",
                                        'ADDRESS': '214 W BOWERY ST', 'CITY': 'AKRON', 'STATE': 'OH', 'ZIP': '44308',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 543-2890', 'TYPE': 'CHILDREN',
                                        'STATUS': 'OPEN', 'POPULATION': 297, 'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153',
                                        'COUNTRY': 'USA', 'LATITUDE': 41.079322093, 'LONGITUDE': -81.525285347,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': "CHILDREN'S HOSPITALS, SPECIALTY (EXCEPT PSYCHIATRIC, SUBSTANCE ABUSE)",
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426032000000,
                                        'WEBSITE': 'https://www.akronchildrens.org/cms/home/index.html',
                                        'STATE_ID': '1277', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 297,
                                        'TRAUMA': 'LEVEL II PEDIATRIC', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6094, 'ID': '0126044308', 'NAME': 'SELECT SPECIALTY HOSPITAL-AKRON',
                                        'ADDRESS': '200 EAST MARKET STREET', 'CITY': 'AKRON', 'STATE': 'OH',
                                        'ZIP': '44308', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 761-7500',
                                        'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN', 'POPULATION': 60,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.082915889, 'LONGITUDE': -81.5117741019999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426032000000,
                                        'WEBSITE': 'http://akron.selectspecialtyhospitals.com/', 'STATE_ID': '1476',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                        'TTL_STAFF': -999, 'BEDS': 60, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 6110, 'ID': '0129144304', 'NAME': 'SUMMA REHAB HOSPITAL',
                                        'ADDRESS': '29 NORTH ADAMS STREET', 'CITY': 'AKRON', 'STATE': 'OH',
                                        'ZIP': '44304', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 572-7300',
                                        'TYPE': 'REHABILITATION', 'STATUS': 'OPEN', 'POPULATION': 60,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.078176985, 'LONGITUDE': -81.498049269, 'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426118400000,
                                        'WEBSITE': 'http://www.summahealth.org/locations/hospitals/summarehabhospital',
                                        'STATE_ID': '1503', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': 60,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 285, 'ID': '0014244266', 'NAME': 'ROBINSON MEMORIAL HOSPITAL',
                                        'ADDRESS': '6847 N CHESTNUT', 'CITY': 'RAVENNA', 'STATE': 'OH', 'ZIP': '44266',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 297-2300',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 302,
                                        'COUNTY': 'PORTAGE', 'COUNTYFIPS': '39133', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.1760577540001, 'LONGITUDE': -81.2490172989999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/portage', 'STATE_ID': '1255',
                                        'ALT_NAME': 'UNIVERSITY HOSPITALS PORTAGE MEDICAL CENTER', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 302, 'TRAUMA': 'LEVEL III',
                                        'HELIPAD': 'Y'}}, {'attributes': {'OBJECTID': 330, 'ID': '0009344221',
                                                                          'NAME': 'EDWIN SHAW REHABILITATION INSTITUTE',
                                                                          'ADDRESS': '330 BROADWAY EAST',
                                                                          'CITY': 'CUYAHOGA FALLS', 'STATE': 'OH',
                                                                          'ZIP': '44221', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(330) 436-0910',
                                                                          'TYPE': 'REHABILITATION', 'STATUS': 'OPEN',
                                                                          'POPULATION': 139, 'COUNTY': 'SUMMIT',
                                                                          'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.1321462700001,
                                                                          'LONGITUDE': -81.47737547,
                                                                          'NAICS_CODE': '622310',
                                                                          'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY',
                                                                          'VAL_DATE': 1391126400000,
                                                                          'WEBSITE': 'http://www.edwinshaw.com',
                                                                          'STATE_ID': '1320',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999,
                                                                          'BEDS': 139, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 1442, 'ID': '0011344310', 'NAME': 'ST THOMAS HOSPITAL',
                                        'ADDRESS': '444 NORTH MAIN STREET', 'CITY': 'AKRON', 'STATE': 'OH',
                                        'ZIP': '44310', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(234) 312-5026',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 392,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.097634392, 'LONGITUDE': -81.514073309, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.summahealth.org/locations/hospitals/stthomas',
                                        'STATE_ID': '1278', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 392,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 1685, 'ID': '0122544310',
                                        'NAME': 'CRYSTAL CLINIC ORTHOPAEDIC CENTER', 'ADDRESS': '444 NORTH MAIN STREET',
                                        'CITY': 'AKRON', 'STATE': 'OH', 'ZIP': '44310', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(330) 762-2262', 'TYPE': 'SPECIAL', 'STATUS': 'OPEN',
                                        'POPULATION': 94, 'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.096930372, 'LONGITUDE': -81.513451264, 'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'ORTHOPEDIC HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1425945600000,
                                        'WEBSITE': 'http://www.crystalclinic.com/locations/akron', 'STATE_ID': '1484',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                        'TTL_STAFF': -999, 'BEDS': 94, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 6494, 'ID': '0007844857', 'NAME': 'FISHER-TITUS HOSPITAL',
                                        'ADDRESS': '272 BENEDICT AVENUE', 'CITY': 'NORWALK', 'STATE': 'OH',
                                        'ZIP': '44857', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(419) 668-8101',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 114,
                                        'COUNTY': 'HURON', 'COUNTYFIPS': '39077', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.2257042730001, 'LONGITUDE': -82.604210251,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.fisher-titus.com', 'STATE_ID': '1204',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 114, 'TRAUMA': 'LEVEL III', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6736, 'ID': '0000544256', 'NAME': 'MEDINA HOSPITAL',
                                        'ADDRESS': '1000 EAST WASHINGTON STREET', 'CITY': 'MEDINA', 'STATE': 'OH',
                                        'ZIP': '44256', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 725-1000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 171,
                                        'COUNTY': 'MEDINA', 'COUNTYFIPS': '39103', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.138450875, 'LONGITUDE': -81.838292925, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.medinahospital.org', 'STATE_ID': '1236',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 171, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 7042, 'ID': '0004744223', 'NAME': 'SUMMA WESTERN RESERVE HOSPITAL',
                                        'ADDRESS': '1900 23RD STREET', 'CITY': 'CUYAHOGA FALLS', 'STATE': 'OH',
                                        'ZIP': '44223', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 971-7000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 272,
                                        'COUNTY': 'SUMMIT', 'COUNTYFIPS': '39153', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.1329909660001, 'LONGITUDE': -81.511095847,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391126400000,
                                        'WEBSITE': 'http://www.westernreservehospital.org', 'STATE_ID': '1280',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                        'TTL_STAFF': -999, 'BEDS': 272, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3005, 'ID': '0005544074', 'NAME': 'MERCY ALLEN HOSPITAL',
                                        'ADDRESS': '200 WEST LORAIN STREET', 'CITY': 'OBERLIN', 'STATE': 'OH',
                                        'ZIP': '44074', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 775-1211',
                                        'TYPE': 'CRITICAL ACCESS', 'STATUS': 'OPEN', 'POPULATION': 25,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.295064762, 'LONGITUDE': -82.224712965, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.mercyonline.org/mercy_allen_hospital.aspx',
                                        'STATE_ID': '1219', 'ALT_NAME': 'ALLEN COMMUNITY HOSPITAL', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 25, 'TRAUMA': 'NOT AVAILABLE',
                                        'HELIPAD': 'Y'}}, {'attributes': {'OBJECTID': 1321, 'ID': '0014344129',
                                                                          'NAME': 'PARMA COMMUNITY GENERAL HOSPITAL',
                                                                          'ADDRESS': '7007 POWERS BOULEVARD',
                                                                          'CITY': 'PARMA', 'STATE': 'OH',
                                                                          'ZIP': '44129', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(440) 743-4900',
                                                                          'TYPE': 'GENERAL ACUTE CARE',
                                                                          'STATUS': 'OPEN', 'POPULATION': 348,
                                                                          'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035',
                                                                          'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.3821198360001,
                                                                          'LONGITUDE': -81.731394677,
                                                                          'NAICS_CODE': '622110',
                                                                          'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY/OTHER',
                                                                          'VAL_DATE': 1394582400000,
                                                                          'WEBSITE': 'www.parmahospital.org',
                                                                          'STATE_ID': '1007',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999,
                                                                          'BEDS': 348, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1688, 'ID': '0124244067',
                                        'NAME': 'NORTHCOAST BEHAVIORAL HEALTHCARE NORTHFIELD CAMPUS',
                                        'ADDRESS': '1756 SAGAMORE ROAD', 'CITY': 'NORTHFIELD', 'STATE': 'OH',
                                        'ZIP': '44067', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(330) 467-7131',
                                        'TYPE': 'PSYCHIATRIC', 'STATUS': 'OPEN', 'POPULATION': -999, 'COUNTY': 'SUMMIT',
                                        'COUNTYFIPS': '39153', 'COUNTRY': 'USA', 'LATITUDE': 41.348951599,
                                        'LONGITUDE': -81.572578469, 'NAICS_CODE': '622210',
                                        'NAICS_DESC': 'PSYCHIATRIC AND SUBSTANCE ABUSE HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1425945600000,
                                        'WEBSITE': 'http://mha.ohio.gov/default.aspx?tabid=190',
                                        'STATE_ID': 'NOT AVAILABLE', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'GOVERNMENT - STATE', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3679, 'ID': '0013544035', 'NAME': 'EMH REGIONAL MEDICAL CENTER',
                                        'ADDRESS': '630 EAST RIVER STREET', 'CITY': 'ELYRIA', 'STATE': 'OH',
                                        'ZIP': '44035', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 329-7500',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 387,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.3668555890001, 'LONGITUDE': -82.097292351,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/elyria', 'STATE_ID': '1217',
                                        'ALT_NAME': 'UNIVERSITY HOSPITALS - ELYRIA MEDICAL CENTER', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 387,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 4106, 'ID': '0007344001', 'NAME': 'SPECIALTY HOSPITAL OF LORAIN',
                                        'ADDRESS': '254 CLEVELAND AVENUE, 2ND FLOOR', 'CITY': 'AMHERST', 'STATE': 'OH',
                                        'ZIP': '44001', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 988-6260',
                                        'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN', 'POPULATION': 30,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.3991966300001, 'LONGITUDE': -82.2235873509999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.specialtyhospitaloflorain.org/', 'STATE_ID': '1433',
                                        'ALT_NAME': 'COMMUNITY SPECIALTY HOSPITAL', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 30, 'TRAUMA': 'NOT AVAILABLE',
                                        'HELIPAD': 'Y'}}, {'attributes': {'OBJECTID': 5916, 'ID': '0027944130',
                                                                          'NAME': 'REGENCY HOSPITAL OF CLEVELAND WEST',
                                                                          'ADDRESS': '6990 ENGLE ROAD',
                                                                          'CITY': 'MIDDLEBURG HEIGHTS', 'STATE': 'OH',
                                                                          'ZIP': '44130', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(717) 975-4503',
                                                                          'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN',
                                                                          'POPULATION': 43, 'COUNTY': 'CUYAHOGA',
                                                                          'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.377357493,
                                                                          'LONGITUDE': -81.827592707,
                                                                          'NAICS_CODE': '622310',
                                                                          'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY/OTHER',
                                                                          'VAL_DATE': 1473897600000,
                                                                          'WEBSITE': 'http://clevelandwest.regencyhospital.com/',
                                                                          'STATE_ID': '1478',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999,
                                                                          'BEDS': 43, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 5931, 'ID': '0004544130', 'NAME': 'SOUTHWEST GENERAL HEALTH CENTER',
                                        'ADDRESS': '18697 BAGLEY ROAD', 'CITY': 'MIDDLEBURG HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44130', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 816-6702',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 362,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.3709924350001, 'LONGITUDE': -81.8320779909999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.swgeneral.com', 'STATE_ID': '1140',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 362, 'TRAUMA': 'LEVEL III', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6975, 'ID': '0011244146', 'NAME': 'UHHS BEDFORD MEDICAL CENTER',
                                        'ADDRESS': '44 BLAINE AVENUE', 'CITY': 'BEDFORD', 'STATE': 'OH', 'ZIP': '44146',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 735-3900',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 88,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.3951438660001, 'LONGITUDE': -81.534072205,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/bedford', 'STATE_ID': '1141',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 88, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1309, 'ID': '0027844111', 'NAME': 'GRACE HOSPITAL AT FAIRVIEW',
                                        'ADDRESS': '18101 LORAIN AVENUE', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44111', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 456-3880',
                                        'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN', 'POPULATION': 29,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4502446440001, 'LONGITUDE': -81.824139117,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'EXTENDED CARE HOSPITALS (EXCEPT MENTAL, SUBSTANCE ABUSE)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1473897600000, 'WEBSITE': 'http://www.gracehospital.org/',
                                        'STATE_ID': '1147', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 29, 'TRAUMA': 'NOT AVAILABLE',
                                        'HELIPAD': 'Y'}}, {'attributes': {'OBJECTID': 1320, 'ID': '0010144122',
                                                                          'NAME': 'UNIVERSITY HOSPITALS AHUJA MEDICAL CENTER',
                                                                          'ADDRESS': '3999 RICHMOND ROAD',
                                                                          'CITY': 'BEACHWOOD', 'STATE': 'OH',
                                                                          'ZIP': '44122', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(216) 593-5500',
                                                                          'TYPE': 'GENERAL ACUTE CARE',
                                                                          'STATUS': 'OPEN', 'POPULATION': 144,
                                                                          'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035',
                                                                          'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.4521988720001,
                                                                          'LONGITUDE': -81.4946935689999,
                                                                          'NAICS_CODE': '622110',
                                                                          'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY',
                                                                          'VAL_DATE': 1391990400000,
                                                                          'WEBSITE': 'http://www.uhhospitals.org/ahuja/',
                                                                          'STATE_ID': '1497',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999,
                                                                          'BEDS': 144, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 2312, 'ID': '0005744122', 'NAME': 'SOUTH POINTE HOSPITAL',
                                        'ADDRESS': '20000 HARVARD ROAD', 'CITY': 'WARRENSVILLE HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44122', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 491-6000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 344,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.447903845, 'LONGITUDE': -81.537736486, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://my.clevelandclinic.org/locations_directions/Regional-Locations/southpointe-hospital',
                                        'STATE_ID': '1297', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 344,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 2319, 'ID': '0028044122', 'NAME': 'HIGHLAND SPRINGS HOSPITAL',
                                        'ADDRESS': '4199 MILL POND DRIVE', 'CITY': 'HIGHLAND HILLS', 'STATE': 'OH',
                                        'ZIP': '44122', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 302-3070',
                                        'TYPE': 'PSYCHIATRIC', 'STATUS': 'OPEN', 'POPULATION': 72, 'COUNTY': 'CUYAHOGA',
                                        'COUNTYFIPS': '39035', 'COUNTRY': 'USA', 'LATITUDE': 41.450390944,
                                        'LONGITUDE': -81.52228096, 'NAICS_CODE': '622210',
                                        'NAICS_DESC': 'PSYCHIATRIC AND SUBSTANCE ABUSE HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1474329600000, 'WEBSITE': 'http://www.highlandspringshealth.com/',
                                        'STATE_ID': '1520', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': 72,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3624, 'ID': '0124844128',
                                        'NAME': 'REGENCY HOSPITAL OF CLEVELAND EAST',
                                        'ADDRESS': '4200 INTERCHANGE CORPORATE CENTER ROAD', 'CITY': 'WARRENSVILLE HTS',
                                        'STATE': 'OH', 'ZIP': '44128', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(216) 910-3800', 'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 44, 'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4322546920001, 'LONGITUDE': -81.5065860349999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426032000000,
                                        'WEBSITE': 'http://clevelandeast.regencyhospital.com/', 'STATE_ID': '1479',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'PROPRIETARY',
                                        'TTL_STAFF': -999, 'BEDS': 44, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3626, 'ID': '0008244145', 'NAME': 'ST JOHN MEDICAL CENTER',
                                        'ADDRESS': '29000 CENTER RIDGE ROAD', 'CITY': 'WESTLAKE', 'STATE': 'OH',
                                        'ZIP': '44145', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 835-8000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 204,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4356459370001, 'LONGITUDE': -81.944736066,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.stjohnmedicalcenter.net/', 'STATE_ID': '1034',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 204, 'TRAUMA': 'LEVEL III', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3627, 'ID': '0129444122',
                                        'NAME': 'UNIVERSITY HOSPITALS REHABILITATION HOSPITAL',
                                        'ADDRESS': '23333 HARVARD ROAD', 'CITY': 'BEACHWOOD', 'STATE': 'OH',
                                        'ZIP': '44122', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 593-2200',
                                        'TYPE': 'REHABILITATION', 'STATUS': 'OPEN', 'POPULATION': 50,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4519197230001, 'LONGITUDE': -81.5101741299999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426118400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/services/rehabilitation-services/uh-rehabilitation-hospital',
                                        'STATE_ID': '1509', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': 50,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3680, 'ID': '0029144011',
                                        'NAME': 'CLEVELAND CLINIC REHABILITATION HOSPITAL, LLC',
                                        'ADDRESS': '33355 HEALTH CAMPUS BOULEVARD', 'CITY': 'AVON', 'STATE': 'OH',
                                        'ZIP': '44011', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 937-9099',
                                        'TYPE': 'REHABILITATION', 'STATUS': 'OPEN', 'POPULATION': 60,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4731324800001, 'LONGITUDE': -81.985816288,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1474416000000,
                                        'WEBSITE': 'http://my.clevelandclinic.org/locations_directions/Regional-Locations/rehabilitation-hospital',
                                        'STATE_ID': '1522', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': 60,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3943, 'ID': '0175344053', 'NAME': 'CLEAR VISTA HEALTH & WELLNESS',
                                        'ADDRESS': '3364 KOLBE ROAD', 'CITY': 'LORAIN', 'STATE': 'OH', 'ZIP': '44053',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 960-7960', 'TYPE': 'PSYCHIATRIC',
                                        'STATUS': 'OPEN', 'POPULATION': -999, 'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093',
                                        'COUNTRY': 'USA', 'LATITUDE': 41.4392418840001, 'LONGITUDE': -82.236045181,
                                        'NAICS_CODE': '622210',
                                        'NAICS_DESC': 'PSYCHIATRIC AND SUBSTANCE ABUSE HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1557360000000, 'WEBSITE': 'http://clearvistahealth.com/',
                                        'STATE_ID': '1518', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3944, 'ID': '0180044011', 'NAME': 'CLEVELAND CLINIC AVON HOSPITAL',
                                        'ADDRESS': '33300 CLEVELAND CLINIC BLVD', 'CITY': 'AVON', 'STATE': 'OH',
                                        'ZIP': '44011', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 636-7727',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 126,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.468906557, 'LONGITUDE': -81.9817664449999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1557360000000,
                                        'WEBSITE': 'https://my.clevelandclinic.org/locations/avon-hospital',
                                        'STATE_ID': 'NOT AVAILABLE', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3945, 'ID': '0170744011',
                                        'NAME': 'UNIVERSITY HOSPITALS AVON REHABILITATION HOSPITAL',
                                        'ADDRESS': '37900 CHESTER ROAD', 'CITY': 'AVON', 'STATE': 'OH', 'ZIP': '44011',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 695-7101',
                                        'TYPE': 'REHABILITATION', 'STATUS': 'OPEN', 'POPULATION': -999,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4680400180001, 'LONGITUDE': -82.0440421709999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1557360000000,
                                        'WEBSITE': 'http://www.uhhospitals.org/uh-avon-rehabilitation-hospital',
                                        'STATE_ID': '1523', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 4013, 'ID': '0169844122', 'NAME': 'GRACE HOSPITAL SOUTH POINTE',
                                        'ADDRESS': '20000 HARVARD ROAD', 'CITY': 'WARRENSVILLE HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44122', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 491-7295',
                                        'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN', 'POPULATION': -999,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4483821170001, 'LONGITUDE': -81.5373010449999,
                                        'NAICS_CODE': '622310',
                                        'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1557360000000, 'WEBSITE': 'http://www.gracehospital.org',
                                        'STATE_ID': 'NOT AVAILABLE', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NOT AVAILABLE', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 5933, 'ID': '0007244109', 'NAME': 'METRO HEALTH MEDICAL CENTER',
                                        'ADDRESS': '2500 METROHEALTH DRIVE', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44109', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 778-7800',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 731,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4609127630001, 'LONGITUDE': -81.697602076,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.metrohealth.org', 'STATE_ID': '1150',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'GOVERNMENT - LOCAL',
                                        'TTL_STAFF': -999, 'BEDS': 731, 'TRAUMA': 'LEVEL I', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 5943, 'ID': '0001844870',
                                        'NAME': 'FIRELANDS REGIONAL MEDICAL CENTER', 'ADDRESS': '1111 HAYES AVENUE',
                                        'CITY': 'SANDUSKY', 'STATE': 'OH', 'ZIP': '44870', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(419) 557-7400', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 283, 'COUNTY': 'ERIE', 'COUNTYFIPS': '39043', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.445892256, 'LONGITUDE': -82.710196917, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.firelands.com', 'STATE_ID': '1164',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 283, 'TRAUMA': 'LEVEL III', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 5946, 'ID': '0028244870',
                                        'NAME': 'FIRELANDS REG MED CTR SOUTH CAMPUS', 'ADDRESS': '1912 HAYES AVENUE',
                                        'CITY': 'SANDUSKY', 'STATE': 'OH', 'ZIP': '44870', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(419) 557-7400', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 141, 'COUNTY': 'ERIE', 'COUNTYFIPS': '39043', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.436997831, 'LONGITUDE': -82.7120100659999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1474329600000, 'WEBSITE': 'http://www.firelands.com',
                                        'STATE_ID': '1165', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 141,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 6007, 'ID': '0009844053', 'NAME': 'MERCY REGIONAL MEDICAL CENTER',
                                        'ADDRESS': '3700 KOLBE ROAD', 'CITY': 'LORAIN', 'STATE': 'OH', 'ZIP': '44053',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 960-4000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 338,
                                        'COUNTY': 'LORAIN', 'COUNTYFIPS': '39093', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4365245390001, 'LONGITUDE': -82.2371635279999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.mercyonline.org/mercy_regional_medical_center.aspx',
                                        'STATE_ID': '1018', 'ALT_NAME': 'COMMUNITY HEALTH PARTNERS', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 338,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6255, 'ID': '0002144125', 'NAME': 'MARYMOUNT HOSPITAL',
                                        'ADDRESS': '12300 MCCRACKEN ROAD', 'CITY': 'GARFIELD HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44125', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 581-0500',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 315,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.421163967, 'LONGITUDE': -81.598029018, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.marymount.org', 'STATE_ID': '1136',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 315, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6969, 'ID': '0004444111', 'NAME': 'FAIRVIEW HOSPITAL',
                                        'ADDRESS': '18101 LORAIN AVENUE', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44111', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 476-4811',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 516,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4505420770001, 'LONGITUDE': -81.8234252789999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.fairviewhospital.org', 'STATE_ID': '1145',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 516, 'TRAUMA': 'LEVEL II', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1319, 'ID': '0017044195', 'NAME': 'CLEVELAND CLINIC',
                                        'ADDRESS': '9500 EUCLID AVENUE', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44195', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 444-2200',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 1268,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.5027509610001, 'LONGITUDE': -81.620792669,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1391990400000, 'WEBSITE': 'http://www.clevelandclinic.org',
                                        'STATE_ID': '1151', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 1268,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3245, 'ID': '0004144113', 'NAME': 'LUTHERAN HOSPITAL',
                                        'ADDRESS': '1730 WEST 25TH STREET', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44113', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 696-4300',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 203,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4876333760001, 'LONGITUDE': -81.707262893,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.lutheranhospital.org', 'STATE_ID': '1149',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 203, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 3623, 'ID': '0122244104',
                                        'NAME': "CLEVELAND CLINIC CHILDREN'S HOSPITAL FOR REHAB",
                                        'ADDRESS': '2801 MARTIN LUTHER KING, JR DRIVE', 'CITY': 'CLEVELAND',
                                        'STATE': 'OH', 'ZIP': '44104', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(216) 448-6440', 'TYPE': 'CHILDREN', 'STATUS': 'OPEN',
                                        'POPULATION': 52, 'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.483056753, 'LONGITUDE': -81.607779934, 'NAICS_CODE': '622310',
                                        'NAICS_DESC': "CHILDREN'S HOSPITALS, SPECIALTY (EXCEPT PSYCHIATRIC, SUBSTANCE ABUSE)",
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1425945600000,
                                        'WEBSITE': 'http://my.clevelandclinic.org/childrens-hospital/specialties-services/therapy-rehab',
                                        'STATE_ID': '1416', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 52, 'TRAUMA': 'NOT AVAILABLE',
                                        'HELIPAD': 'N'}}, {'attributes': {'OBJECTID': 4449, 'ID': '0123444120',
                                                                          'NAME': 'SELECT SPECIALTY HOSPITAL - CLEVELAND FAIRHILL',
                                                                          'ADDRESS': '11900 FAIRHILL ROAD',
                                                                          'CITY': 'CLEVELAND', 'STATE': 'OH',
                                                                          'ZIP': '44120', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(216) 231-2094',
                                                                          'TYPE': 'LONG TERM CARE', 'STATUS': 'OPEN',
                                                                          'POPULATION': 68, 'COUNTY': 'CUYAHOGA',
                                                                          'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.4899792640001,
                                                                          'LONGITUDE': -81.5984828209999,
                                                                          'NAICS_CODE': '622310',
                                                                          'NAICS_DESC': 'SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY/OTHER',
                                                                          'VAL_DATE': 1425945600000,
                                                                          'WEBSITE': 'http://clevelandfairhill.selectspecialtyhospitals.com/',
                                                                          'STATE_ID': '1468',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999,
                                                                          'BEDS': 68, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 5914, 'ID': '0003544107', 'NAME': 'LAKEWOOD HOSPITAL',
                                        'ADDRESS': '14519 DETROIT AVENUE', 'CITY': 'LAKEWOOD', 'STATE': 'OH',
                                        'ZIP': '44107', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 521-4200',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'CLOSED', 'POPULATION': 263,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.4841907050001, 'LONGITUDE': -81.796605578,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Default.aspx',
                                        'SOURCEDATE': 1473811200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://my.clevelandclinic.org/locations_directions/Regional-Locations/lakewood',
                                        'STATE_ID': '1134', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 263,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 7427, 'ID': '0122944113', 'NAME': 'GRACE HOSPITAL',
                                        'ADDRESS': '2307 WEST 14TH STREET', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44113', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 456-3891',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'CLOSED', 'POPULATION': -999,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.480695299, 'LONGITUDE': -81.690868471, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov', 'SOURCEDATE': 1425340800000,
                                        'VAL_METHOD': 'IMAGERY/OTHER', 'VAL_DATE': 1425945600000,
                                        'WEBSITE': 'NOT AVAILABLE', 'STATE_ID': 'NOT AVAILABLE',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NOT AVAILABLE',
                                        'TTL_STAFF': -999, 'BEDS': -999, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 1318, 'ID': '0001744106',
                                        'NAME': 'UNIVERSITY HOSPITALS OF CLEVELAND', 'ADDRESS': '11100 EUCLID AVENUE',
                                        'CITY': 'CLEVELAND', 'STATE': 'OH', 'ZIP': '44106', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(216) 844-1000', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 1032, 'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035',
                                        'COUNTRY': 'USA', 'LATITUDE': 41.506142051, 'LONGITUDE': -81.605095434,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/cleveland', 'STATE_ID': '1142',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 1032, 'TRAUMA': 'LEVEL I', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 1482, 'ID': '0001244106',
                                        'NAME': 'LOUIS STOKES CLEVELAND VETERANS AFFAIRS MEDICAL CENTER',
                                        'ADDRESS': '10701 EAST BLVD', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44106', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 791-3800',
                                        'TYPE': 'MILITARY', 'STATUS': 'OPEN', 'POPULATION': 585, 'COUNTY': 'CUYAHOGA',
                                        'COUNTYFIPS': '39035', 'COUNTRY': 'USA', 'LATITUDE': 41.5132563880001,
                                        'LONGITUDE': -81.613703544, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391472000000,
                                        'WEBSITE': 'http://www.cleveland.va.gov/', 'STATE_ID': '36001F',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'GOVERNMENT - FEDERAL',
                                        'TTL_STAFF': -999, 'BEDS': 585, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 1690, 'ID': '0124744106',
                                        'NAME': 'RAINBOW BABIES AND CHILDRENS HOSPITAL',
                                        'ADDRESS': '11100 EUCLID AVENUE', 'CITY': 'CLEVELAND', 'STATE': 'OH',
                                        'ZIP': '44106', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 844-1000',
                                        'TYPE': 'CHILDREN', 'STATUS': 'OPEN', 'POPULATION': -999, 'COUNTY': 'CUYAHOGA',
                                        'COUNTYFIPS': '39035', 'COUNTRY': 'USA', 'LATITUDE': 41.507561206,
                                        'LONGITUDE': -81.605813744, 'NAICS_CODE': '622310',
                                        'NAICS_DESC': "CHILDREN'S HOSPITALS, SPECIALTY (EXCEPT PSYCHIATRIC, SUBSTANCE ABUSE)",
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426032000000, 'WEBSITE': 'http://www.uhhospitals.org/rainbow',
                                        'STATE_ID': 'NOT AVAILABLE', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': -999,
                                        'TRAUMA': 'LEVEL I PEDIATRIC', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 2320, 'ID': '0004644119', 'NAME': 'EUCLID HOSPITAL',
                                        'ADDRESS': '18901 LAKE SHORE BOULEVARD', 'CITY': 'EUCLID', 'STATE': 'OH',
                                        'ZIP': '44119', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(216) 531-9000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 371,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.5988940500001, 'LONGITUDE': -81.5487775189999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.euclidhospital.org', 'STATE_ID': '1133',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 371, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 5909, 'ID': '0014144124', 'NAME': 'HILLCREST HOSPITAL',
                                        'ADDRESS': '6780 MAYFIELD ROAD', 'CITY': 'MAYFIELD HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44124', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 312-4415',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 500,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.518299927, 'LONGITUDE': -81.436247882, 'NAICS_CODE': '622110',
                                        'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'http://my.clevelandclinic.org/locations_directions/Regional-Locations/hillcrest-hospital',
                                        'STATE_ID': '1019', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 500, 'TRAUMA': 'LEVEL II',
                                        'HELIPAD': 'Y'}}, {'attributes': {'OBJECTID': 5998, 'ID': '0123244024',
                                                                          'NAME': 'REHAB HOSPITAL AT HEATHER HILL CARE COMMUNITIES',
                                                                          'ADDRESS': '12340 BASS LAKE ROAD',
                                                                          'CITY': 'CHARDON', 'STATE': 'OH',
                                                                          'ZIP': '44024', 'ZIP4': 'NOT AVAILABLE',
                                                                          'TELEPHONE': '(440) 285-4040',
                                                                          'TYPE': 'REHABILITATION', 'STATUS': 'OPEN',
                                                                          'POPULATION': 56, 'COUNTY': 'GEAUGA',
                                                                          'COUNTYFIPS': '39055', 'COUNTRY': 'USA',
                                                                          'LATITUDE': 41.5357085960001,
                                                                          'LONGITUDE': -81.223012292,
                                                                          'NAICS_CODE': '622310',
                                                                          'NAICS_DESC': 'REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, DRUG ADDICTION)',
                                                                          'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                                                          'SOURCEDATE': 1533859200000,
                                                                          'VAL_METHOD': 'IMAGERY/OTHER',
                                                                          'VAL_DATE': 1425945600000,
                                                                          'WEBSITE': 'http://www.heatherhillcare.com/',
                                                                          'STATE_ID': '1420',
                                                                          'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                                                          'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999,
                                                                          'BEDS': 56, 'TRAUMA': 'NOT AVAILABLE',
                                                                          'HELIPAD': 'N'}}, {
                         'attributes': {'OBJECTID': 6919, 'ID': '0002644024', 'NAME': 'UH GEAUGA MEDICAL CENTER',
                                        'ADDRESS': '13207 RAVENNA RD', 'CITY': 'CHARDON', 'STATE': 'OH', 'ZIP': '44024',
                                        'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 285-6000',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 225,
                                        'COUNTY': 'GEAUGA', 'COUNTYFIPS': '39055', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.5092579970001, 'LONGITUDE': -81.1890927919999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.uhhospitals.org/geauga/', 'STATE_ID': '1001',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 225, 'TRAUMA': 'LEVEL III', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6972, 'ID': '0007744143', 'NAME': 'UHHS RICHMOND HEIGHTS HOSPITAL',
                                        'ADDRESS': '27100 CHARDON ROAD', 'CITY': 'RICHMOND HEIGHTS', 'STATE': 'OH',
                                        'ZIP': '44143', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 585-6500',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 213,
                                        'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.5807521290001, 'LONGITUDE': -81.4889102339999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'www.uhhospitals.org/richmond', 'STATE_ID': '1008',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 213, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6974, 'ID': '0006844115',
                                        'NAME': 'ST VINCENT CHARITY MEDICAL CENTER', 'ADDRESS': '2351 EAST 22ND STREET',
                                        'CITY': 'CLEVELAND', 'STATE': 'OH', 'ZIP': '44115', 'ZIP4': 'NOT AVAILABLE',
                                        'TELEPHONE': '(216) 861-6200', 'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN',
                                        'POPULATION': 448, 'COUNTY': 'CUYAHOGA', 'COUNTYFIPS': '39035',
                                        'COUNTRY': 'USA', 'LATITUDE': 41.4958505380001, 'LONGITUDE': -81.6731148549999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1394582400000,
                                        'WEBSITE': 'https://www.stvincentcharity.com/', 'STATE_ID': '1155',
                                        'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39', 'OWNER': 'NON-PROFIT',
                                        'TTL_STAFF': -999, 'BEDS': 448, 'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 3677, 'ID': '0015044077', 'NAME': 'TRIPOINT MEDICAL CENTER',
                                        'ADDRESS': '7590 AUBURN ROAD', 'CITY': 'PAINESVILLE', 'STATE': 'OH',
                                        'ZIP': '44077', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 375-8100',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 135,
                                        'COUNTY': 'LAKE', 'COUNTYFIPS': '39085', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.6626096360001, 'LONGITUDE': -81.247080777,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY', 'VAL_DATE': 1391990400000,
                                        'WEBSITE': 'http://www.lakehealth.org/Locations/TriPoint-Medical-Center',
                                        'STATE_ID': '1211', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 135,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6495, 'ID': '0129644094',
                                        'NAME': 'WINDSOR LAURELWOOD CENTER FOR BEHAVORIAL MEDICINE',
                                        'ADDRESS': '35900 EUCLID AVENUE', 'CITY': 'WILLOUGHBY', 'STATE': 'OH',
                                        'ZIP': '44094', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 953-3000',
                                        'TYPE': 'PSYCHIATRIC', 'STATUS': 'OPEN', 'POPULATION': 159, 'COUNTY': 'LAKE',
                                        'COUNTYFIPS': '39085', 'COUNTRY': 'USA', 'LATITUDE': 41.624742869,
                                        'LONGITUDE': -81.433562217, 'NAICS_CODE': '622210',
                                        'NAICS_DESC': 'PSYCHIATRIC AND SUBSTANCE ABUSE HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1426118400000, 'WEBSITE': 'http://www.windsorlaurelwood.com/',
                                        'STATE_ID': '1538', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'PROPRIETARY', 'TTL_STAFF': -999, 'BEDS': 159,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}, {
                         'attributes': {'OBJECTID': 6496, 'ID': '0028844094', 'NAME': 'LAKE WEST HOSPITAL',
                                        'ADDRESS': '36000 EUCLID AVENUE', 'CITY': 'WILLOUGHBY', 'STATE': 'OH',
                                        'ZIP': '44094', 'ZIP4': 'NOT AVAILABLE', 'TELEPHONE': '(440) 375-8100',
                                        'TYPE': 'GENERAL ACUTE CARE', 'STATUS': 'OPEN', 'POPULATION': 267,
                                        'COUNTY': 'LAKE', 'COUNTYFIPS': '39085', 'COUNTRY': 'USA',
                                        'LATITUDE': 41.625718448, 'LONGITUDE': -81.4322059249999,
                                        'NAICS_CODE': '622110', 'NAICS_DESC': 'GENERAL MEDICAL AND SURGICAL HOSPITALS',
                                        'SOURCE': 'http://publicapps.odh.ohio.gov/EID/Provider_Search.aspx',
                                        'SOURCEDATE': 1533859200000, 'VAL_METHOD': 'IMAGERY/OTHER',
                                        'VAL_DATE': 1474416000000,
                                        'WEBSITE': 'http://www.lakehealth.org/Locations/West-Medical-Center',
                                        'STATE_ID': '1006', 'ALT_NAME': 'NOT AVAILABLE', 'ST_FIPS': '39',
                                        'OWNER': 'NON-PROFIT', 'TTL_STAFF': -999, 'BEDS': 267,
                                        'TRAUMA': 'NOT AVAILABLE', 'HELIPAD': 'Y'}}]


test_yaml = """
- send:
    message: Welcome to Sequoia! What is your 5-digit ZIP code?
- receive:
    key: zip_code
    expect_type: int
    on_failure: retry
- send:
    message: What is your temperature today? Answer 0 if you do not have a thermometer.
- receive:
    key: temperature
    expect_type: float
    on_failure: retry
- send:
    message: Did you have or feel like you have had a fever in the last 24 hours? Y/N
- receive:
    key: fever
    expect_type: str
    on_failure: retry
- send:
    message: Do you have a new or worsening cough? Y/N
- receive:
    key: cough
    expect_type: str
    on_failure: retry
- send:
    message: Are you having trouble breathing? Y/N
- receive:
    key: trouble_breathing
    expect_type: str
    on_failure: retry
- send:
    message: Do you have new or worsening body aches? Y/N
- receive:
    key: body_aches
    expect_type: str
    on_failure: retry
- send:
    message: Do you have a sore throat, different from your seasonal allergies? Y/N
- receive:
    key: sore_throat
    expect_type: str
    on_failure: retry
- send:
    message: Hang tight, getting an expert opinion...
"""